- hosts: kube-test-manager
  become: True
  tasks:
    - name: Install PIP
      apt:
        name: python3-pip

    - name: Install Python modules
      pip:
        name:
          - openshift
          - kubernetes
